name: UiPath CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install UiPath CLI
      run: dotnet tool install --global UiPath.CLI.Windows

    - name: Add CLI to PATH
      run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

    # 🔥 FIX: Clear broken cache (solves Process.Activities error)
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Pack project
      run: uipcli package pack project.json -o output

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: uipath-package
        path: output

    - name: Debug Secrets
      run: |
       echo "ORG=${{ secrets.UIPATH_ORG }}"
            echo "TENANT=${{ secrets.UIPATH_TENANT }}"
  
    - name: Deploy Package
      run: |
        uipcli package deploy output/*.nupkg https://cloud.uipath.com/${{ secrets.UIPATH_ORG }} ${{ secrets.UIPATH_TENANT }} -A ${{ secrets.UIPATH_ORG }} -I ${{ secrets.UIPATH_CLIENT_ID }} -S ${{ secrets.UIPATH_CLIENT_SECRET }} --identityUrl https://cloud.uipath.com/identity -o "My Workspace"

    - name: Done
      run: echo "Pipeline completed"